version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    restart: unless-stopped
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
networks:
  mongodb_network:
    driver: bridge
